//! Message-related models

use crate::channel::Channel;
use crate::guild::Member;
use crate::id::{AttachmentId, ChannelId, GuildId, MessageId, RoleId, UserId, WebhookId};
use crate::user::User;
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

/// Represents a message sent in a channel.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Message {
    /// ID of the message.
    pub id: MessageId,
    /// ID of the channel the message was sent in.
    pub channel_id: ChannelId,
    /// The author of this message.
    pub author: User,
    /// Contents of the message.
    pub content: String,
    /// When this message was sent.
    pub timestamp: String,
    /// When this message was edited (or null if never).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub edited_timestamp: Option<String>,
    /// Whether this was a TTS message.
    pub tts: bool,
    /// Whether this message mentions everyone.
    pub mention_everyone: bool,
    /// Users specifically mentioned in the message.
    #[serde(default)]
    pub mentions: Vec<User>,
    /// Roles specifically mentioned in this message.
    #[serde(default)]
    pub mention_roles: Vec<RoleId>,
    /// Channels specifically mentioned in this message.
    #[serde(default)]
    pub mention_channels: Vec<ChannelMention>,
    /// Any attached files.
    #[serde(default)]
    pub attachments: Vec<Attachment>,
    /// Any embedded content.
    #[serde(default)]
    pub embeds: Vec<Embed>,
    /// Reactions to the message.
    #[serde(default)]
    pub reactions: Vec<Reaction>,
    /// Used for validating a message was sent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nonce: Option<serde_json::Value>,
    /// Whether this message is pinned.
    pub pinned: bool,
    /// If the message is generated by a webhook, this is the webhook's ID.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook_id: Option<WebhookId>,
    /// Type of message.
    #[serde(rename = "type")]
    pub kind: MessageType,
    /// Sent with Rich Presence-related chat embeds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub activity: Option<MessageActivity>,
    /// Sent with Rich Presence-related chat embeds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub application: Option<MessageApplication>,
    /// If the message is an Interaction or application-owned webhook.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub application_id: Option<UserId>,
    /// Data showing the source of a crosspost, channel follow add, pin, or reply message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_reference: Option<MessageReference>,
    /// Message flags.
    #[serde(default)]
    pub flags: u32,
    /// The message associated with the message_reference.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub referenced_message: Option<Box<Message>>,
    /// Sent if the message is a response to an Interaction.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub interaction: Option<MessageInteraction>,
    /// The thread that was started from this message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thread: Option<Channel>,
    /// Sent if the message contains components like buttons, action rows, or other interactive components.
    #[serde(default)]
    pub components: Vec<Component>,
    /// Sent if the message contains stickers.
    #[serde(default)]
    pub sticker_items: Vec<StickerItem>,
    /// A generally increasing integer that represents the approximate position of the message in a thread.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position: Option<u32>,
    /// The guild ID of the message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub guild_id: Option<GuildId>,
    /// Member properties for this message's author.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub member: Option<Member>,
}

impl Message {
    /// Returns a URL that links to this message.
    pub fn jump_url(&self) -> String {
        match self.guild_id {
            Some(guild_id) => format!(
                "https://discord.com/channels/{}/{}/{}",
                guild_id, self.channel_id, self.id
            ),
            None => format!(
                "https://discord.com/channels/@me/{}/{}",
                self.channel_id, self.id
            ),
        }
    }

    /// Returns true if this message is a system message.
    pub fn is_system(&self) -> bool {
        !matches!(self.kind, MessageType::Default | MessageType::Reply)
    }
}

/// Type of message.
#[derive(Clone, Copy, Debug, Default, Deserialize_repr, Serialize_repr, PartialEq, Eq)]
#[repr(u8)]
pub enum MessageType {
    #[default]
    Default = 0,
    RecipientAdd = 1,
    RecipientRemove = 2,
    Call = 3,
    ChannelNameChange = 4,
    ChannelIconChange = 5,
    ChannelPinnedMessage = 6,
    UserJoin = 7,
    GuildBoost = 8,
    GuildBoostTier1 = 9,
    GuildBoostTier2 = 10,
    GuildBoostTier3 = 11,
    ChannelFollowAdd = 12,
    GuildDiscoveryDisqualified = 14,
    GuildDiscoveryRequalified = 15,
    GuildDiscoveryGracePeriodInitialWarning = 16,
    GuildDiscoveryGracePeriodFinalWarning = 17,
    ThreadCreated = 18,
    Reply = 19,
    ChatInputCommand = 20,
    ThreadStarterMessage = 21,
    GuildInviteReminder = 22,
    ContextMenuCommand = 23,
    AutoModerationAction = 24,
    RoleSubscriptionPurchase = 25,
    InteractionPremiumUpsell = 26,
    StageStart = 27,
    StageEnd = 28,
    StageSpeaker = 29,
    StageTopic = 31,
    GuildApplicationPremiumSubscription = 32,
}

/// Represents a file attached to a message.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Attachment {
    /// Attachment ID.
    pub id: AttachmentId,
    /// Name of file attached.
    pub filename: String,
    /// Description for the file.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The attachment's media type.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    /// Size of file in bytes.
    pub size: u64,
    /// Source URL of file.
    pub url: String,
    /// A proxied URL of file.
    pub proxy_url: String,
    /// Height of file (if image).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<u32>,
    /// Width of file (if image).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<u32>,
    /// Whether this attachment is ephemeral.
    #[serde(default)]
    pub ephemeral: bool,
    /// The duration of the audio file (currently for voice messages).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_secs: Option<f64>,
    /// Base64 encoded bytearray representing a sampled waveform.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub waveform: Option<String>,
    /// Attachment flags.
    #[serde(default)]
    pub flags: u32,
}

impl Attachment {
    /// Returns true if this attachment is an image.
    pub fn is_image(&self) -> bool {
        self.content_type
            .as_ref()
            .map(|ct| ct.starts_with("image/"))
            .unwrap_or(false)
    }

    /// Returns true if this attachment is a video.
    pub fn is_video(&self) -> bool {
        self.content_type
            .as_ref()
            .map(|ct| ct.starts_with("video/"))
            .unwrap_or(false)
    }

    /// Returns true if this attachment is audio.
    pub fn is_audio(&self) -> bool {
        self.content_type
            .as_ref()
            .map(|ct| ct.starts_with("audio/"))
            .unwrap_or(false)
    }

    /// Returns true if this attachment is spoilered.
    pub fn is_spoiler(&self) -> bool {
        self.filename.starts_with("SPOILER_")
    }
}

/// Represents an embed in a message.
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct Embed {
    /// Title of embed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Type of embed (always "rich" for webhook embeds).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// Description of embed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// URL of embed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Timestamp of embed content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// Color code of the embed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<u32>,
    /// Footer information.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footer: Option<EmbedFooter>,
    /// Image information.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image: Option<EmbedImage>,
    /// Thumbnail information.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<EmbedThumbnail>,
    /// Video information.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video: Option<EmbedVideo>,
    /// Provider information.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider: Option<EmbedProvider>,
    /// Author information.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author: Option<EmbedAuthor>,
    /// Fields information.
    #[serde(default)]
    pub fields: Vec<EmbedField>,
}

impl Embed {
    /// Create a new embed builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the title of the embed.
    pub fn title(mut self, title: impl Into<String>) -> Self {
        self.title = Some(title.into());
        self
    }

    /// Set the description of the embed.
    pub fn description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    /// Set the URL of the embed.
    pub fn url(mut self, url: impl Into<String>) -> Self {
        self.url = Some(url.into());
        self
    }

    /// Set the color of the embed.
    pub fn color(mut self, color: u32) -> Self {
        self.color = Some(color);
        self
    }

    /// Add a field to the embed.
    pub fn field(
        mut self,
        name: impl Into<String>,
        value: impl Into<String>,
        inline: bool,
    ) -> Self {
        self.fields.push(EmbedField {
            name: name.into(),
            value: value.into(),
            inline,
        });
        self
    }
}

/// Embed footer.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct EmbedFooter {
    /// Footer text.
    pub text: String,
    /// URL of footer icon.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon_url: Option<String>,
    /// A proxied URL of footer icon.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy_icon_url: Option<String>,
}

/// Embed image.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct EmbedImage {
    /// Source URL of image.
    pub url: String,
    /// A proxied URL of the image.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy_url: Option<String>,
    /// Height of image.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<u32>,
    /// Width of image.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<u32>,
}

/// Embed thumbnail.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct EmbedThumbnail {
    /// Source URL of thumbnail.
    pub url: String,
    /// A proxied URL of the thumbnail.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy_url: Option<String>,
    /// Height of thumbnail.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<u32>,
    /// Width of thumbnail.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<u32>,
}

/// Embed video.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct EmbedVideo {
    /// Source URL of video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// A proxied URL of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy_url: Option<String>,
    /// Height of video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<u32>,
    /// Width of video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<u32>,
}

/// Embed provider.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct EmbedProvider {
    /// Name of provider.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// URL of provider.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// Embed author.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct EmbedAuthor {
    /// Name of author.
    pub name: String,
    /// URL of author.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// URL of author icon.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon_url: Option<String>,
    /// A proxied URL of author icon.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy_icon_url: Option<String>,
}

/// Embed field.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct EmbedField {
    /// Name of the field.
    pub name: String,
    /// Value of the field.
    pub value: String,
    /// Whether or not this field should display inline.
    #[serde(default)]
    pub inline: bool,
}

/// Channel mention in a message.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ChannelMention {
    /// ID of the channel.
    pub id: ChannelId,
    /// ID of the guild containing the channel.
    pub guild_id: GuildId,
    /// The type of channel.
    #[serde(rename = "type")]
    pub kind: crate::channel::ChannelType,
    /// The name of the channel.
    pub name: String,
}

/// Reaction to a message.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Reaction {
    /// Times this emoji has been used to react.
    pub count: u32,
    /// Reaction count details object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count_details: Option<ReactionCountDetails>,
    /// Whether the current user reacted using this emoji.
    pub me: bool,
    /// Whether the current user super-reacted using this emoji.
    #[serde(default)]
    pub me_burst: bool,
    /// Emoji information.
    pub emoji: crate::guild::Emoji,
    /// HEX colors used for super reaction.
    #[serde(default)]
    pub burst_colors: Vec<String>,
}

/// Reaction count details.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ReactionCountDetails {
    /// Count of super reactions.
    pub burst: u32,
    /// Count of normal reactions.
    pub normal: u32,
}

/// Message activity.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MessageActivity {
    /// Type of message activity.
    #[serde(rename = "type")]
    pub kind: u8,
    /// party_id from a Rich Presence event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub party_id: Option<String>,
}

/// Message application.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MessageApplication {
    /// ID of the application.
    pub id: UserId,
    /// ID of the embed's image asset.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cover_image: Option<String>,
    /// Application's description.
    pub description: String,
    /// ID of the application's icon.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    /// Name of the application.
    pub name: String,
}

/// Message reference.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MessageReference {
    /// ID of the originating message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_id: Option<MessageId>,
    /// ID of the originating message's channel.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<ChannelId>,
    /// ID of the originating message's guild.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub guild_id: Option<GuildId>,
    /// When sending, whether to error if the referenced message doesn't exist.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fail_if_not_exists: Option<bool>,
}

/// Message interaction.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MessageInteraction {
    /// ID of the interaction.
    pub id: UserId,
    /// Type of interaction.
    #[serde(rename = "type")]
    pub kind: u8,
    /// Name of the application command.
    pub name: String,
    /// User who invoked the interaction.
    pub user: User,
    /// Member who invoked the interaction in the guild.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub member: Option<Member>,
}

/// Message component.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Component {
    /// Component type.
    #[serde(rename = "type")]
    pub kind: ComponentType,
    /// Components within this component (for action rows).
    #[serde(default)]
    pub components: Vec<Component>,
    /// Button style.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub style: Option<u8>,
    /// Text that appears on the button.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Emoji that appears on the button.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub emoji: Option<crate::guild::Emoji>,
    /// Developer-defined identifier for the component.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_id: Option<String>,
    /// URL for link-style buttons.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Whether the component is disabled.
    #[serde(default)]
    pub disabled: bool,
    /// Choices for select menus.
    #[serde(default)]
    pub options: Vec<SelectOption>,
    /// Placeholder text for select menus.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub placeholder: Option<String>,
    /// Minimum number of items that must be chosen.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_values: Option<u32>,
    /// Maximum number of items that can be chosen.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_values: Option<u32>,
    /// Minimum input length for text inputs.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_length: Option<u32>,
    /// Maximum input length for text inputs.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_length: Option<u32>,
    /// Whether this component is required to be filled.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    /// Pre-filled value for text inputs.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// Component type.
#[derive(Clone, Copy, Debug, Default, Deserialize_repr, Serialize_repr, PartialEq, Eq)]
#[repr(u8)]
pub enum ComponentType {
    /// Container for other components.
    #[default]
    ActionRow = 1,
    /// Button object.
    Button = 2,
    /// Select menu for picking from defined text options.
    StringSelect = 3,
    /// Text input object.
    TextInput = 4,
    /// Select menu for users.
    UserSelect = 5,
    /// Select menu for roles.
    RoleSelect = 6,
    /// Select menu for mentionables (users and roles).
    MentionableSelect = 7,
    /// Select menu for channels.
    ChannelSelect = 8,
}

/// Select menu option.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SelectOption {
    /// User-facing name of the option.
    pub label: String,
    /// Dev-defined value of the option.
    pub value: String,
    /// Additional description of the option.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Emoji that appears on the option.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub emoji: Option<crate::guild::Emoji>,
    /// Whether this option is selected by default.
    #[serde(default)]
    pub default: bool,
}

/// Sticker item.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct StickerItem {
    /// ID of the sticker.
    pub id: UserId,
    /// Name of the sticker.
    pub name: String,
    /// Type of sticker format.
    pub format_type: u8,
}
